### ISSUE TITLE
running issue

### ISSUE THREAD

**Issue by gregdp** [kiharalab/DAQ#1]
I get the following output when running the code:

mrc.c: In function ‘readmrc’:
mrc.c:193:11: error: ‘for’ loop initial declarations are only allowed in C99 mode
           for(int i = 0; i<mrc->NumVoxels; ++i)
…
sh: /scratch/g/gregp/daq/DAQ/process_map/gen_trimmap/TrimMapAtom: No such file or directory

**Comment by wang3702** [comment]
Thanks a lot for your interest in our work! Sorry for the late response. Could you please run "make" under this directory: process_map/gen_trimmap. I believe it should fix the bug. Also, please try our colab platform: https://bit.ly/daq-score, it works fine here. I just tested it today.

**Comment by wang3702** [comment]
Also, could you please provide your environment details so that we can possibly reproduce your error on my side:
Operation System:
PyTorch version: 
Python version:
CUDA/cuDNN version: 
GPU models and configuration:
