### ISSUE TITLE
Two make errors and Assign score compilation failed

### ISSUE THREAD

**Issue by ShuwenZh** [kiharalab/DAQ#4]
Hi, I tried to run the script, but failed with output as follows:

resizing finished!
make: *** No rule to make target 'clean'.  Stop.
gcc -O3 -c chkcmdline.c
gcc -O3 -c mrc.c -lm -O3 -msse4.2 -msse -msse2 -msse3 -mmmx -ftree-vectorize -ftree-vectorizer-verbose=3 -ffast-math -march=native -funroll-loops -fopenmp
gcc -O3 -c readpdb.c -lm -O3 -msse4.2 -msse -msse2 -msse3 -mmmx -ftree-vectorize -ftree-vectorizer-verbose=3 -ffast-math -march=native -funroll-loops -fopenmp
gcc -o TrimMapAtom main.c chkcmdline.o mrc.o readpdb.o -lm -O3 -msse4.2 -msse -msse2 -msse3 -mmmx -ftree-vectorize -ftree-vectorizer-verbose=3 -ffast-math -march=native -funroll-loops -fopenmp 
/usr/bin/ld: chkcmdline.o:(.bss+0x0): multiple definition of `FINAL_RENo'; /tmp/cc5lck8g.o:(.bss+0x3c8): first defined here
/usr/bin/ld: chkcmdline.o:(.bss+0x4): multiple definition of `FINAL_ATNo'; /tmp/cc5lck8g.o:(.bss+0x3cc): first defined here
/usr/bin/ld: mrc.o:(.bss+0x0): multiple definition of `FINAL_RENo'; /tmp/cc5lck8g.o:(.bss+0x3c8): first defined here
/usr/bin/ld: mrc.o:(.bss+0x4): multiple definition of `FINAL_ATNo'; /tmp/cc5lck8g.o:(.bss+0x3cc): first defined here
/usr/bin/ld: readpdb.o:(.bss+0x0): multiple definition of `FINAL_RENo'; /tmp/cc5lck8g.o:(.bss+0x3c8): first defined here
/usr/bin/ld: readpdb.o:(.bss+0x4): multiple definition of `FINAL_ATNo'; /tmp/cc5lck8g.o:(.bss+0x3cc): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:13: TrimMapAtom] Error 1
sh: 1: /ldata/swzhang/DAQ/process_map/gen_trimmap/TrimMapAtom: not found
Finished processing model input!
Our predictions are saved in /ldata/swzhang/DAQ/Predict_Result/ed21_max_sharpened_spacing1/prediction.txt, please have a check!
gcc -std=c99 -o DAQscore_colab main.c chkcmdline.o mrc.o readpdb.o thread.o dp.o -lm -O3 -msse4.2 -msse -msse2 -msse3 -mmmx -ftree-vectorize -ftree-vectorizer-verbose=3 -ffast-math -march=native -funroll-loops -fopenmp 
/usr/bin/ld: chkcmdline.o:(.bss+0x0): multiple definition of `FINAL_RENo'; /tmp/ccitTEq4.o:(.bss+0x488): first defined here
/usr/bin/ld: chkcmdline.o:(.bss+0x4): multiple definition of `FINAL_ATNo'; /tmp/ccitTEq4.o:(.bss+0x48c): first defined here
/usr/bin/ld: mrc.o:(.bss+0x0): multiple definition of `FINAL_RENo'; /tmp/ccitTEq4.o:(.bss+0x488): first defined here
/usr/bin/ld: mrc.o:(.bss+0x4): multiple definition of `FINAL_ATNo'; /tmp/ccitTEq4.o:(.bss+0x48c): first defined here
/usr/bin/ld: readpdb.o:(.bss+0x0): multiple definition of `FINAL_RENo'; /tmp/ccitTEq4.o:(.bss+0x488): first defined here
/usr/bin/ld: readpdb.o:(.bss+0x4): multiple definition of `FINAL_ATNo'; /tmp/ccitTEq4.o:(.bss+0x48c): first defined here
/usr/bin/ld: thread.o:(.bss+0x0): multiple definition of `FINAL_RENo'; /tmp/ccitTEq4.o:(.bss+0x488): first defined here
/usr/bin/ld: thread.o:(.bss+0x4): multiple definition of `FINAL_ATNo'; /tmp/ccitTEq4.o:(.bss+0x48c): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:13: DAQscore_colab] Error 1
Assign score compilation failed! Please make contact with dkihara@purdue.edu!
Traceback (most recent call last):
  File "main.py", line 52, in <module>
    exe_path = compile_online(daq_code_path)
  File "main.py", line 15, in compile_online
    assert os.path.exists(exe_path)
AssertionError

**Comment by wang3702** [comment]
Thank you for your attention to our work! We did not encounter this error before. Which OS did you use to run DAQ? If you use MacOS, then it may be the operating system did not work well for compilation. Also, if you want, I think you can try our colab online platform in https://bit.ly/daq-score before we figured out your problem.

**Comment by ShuwenZh** [comment]
Thanks, it seems to be correlated with the OS. It failed on Ubuntu 22.04. Then I tried this with another PC on Ubuntu 20.04 and it worked. Or maybe it's because of the version of gcc or something else? The default gcc version is 11.2.0 on Ubuntu 22.04 and 9.4.0 on Ubuntu 20.04.

**Comment by wang3702** [comment]
Glad to know that! I think it's because the internal staff has changed in the newer version of ubuntu. I don't think the GCC version can impact too much on our software.
